shm_size: '32G'
export_format: 'ark:raw'
samples_per_gpu: 16
workers_per_gpu: 8
max_epochs: 300
config_file: 'configs/yolox/yolox_tiny_8x8_300e_coco.py'
args_options: ''
cfg_options: ''
metric: 'bbox'
val_interval: 0  # <0 means use auto interval = max(1, max_epochs//10)
port: 12345
