# training template for your executor app
# after build image, it should at /img-man/training-template.yaml
# key: gpu_id, task_id, pretrained_model_params, class_names should be preserved

# gpu_id: '0'
# task_id: 'default-training-task'
# pretrained_model_params: []
# class_names: []

shm_size: '32G'
export_format: 'ark:raw'
model: 'yolov5s'
batch_size_per_gpu: 16
epochs: 300
img_size: 640
opset: 11
args_options: '--exist-ok'
save_period: 10
sync_bn: False # work for multi-gpu only
