# * image_height, image_width and anchors should be the same with corresponding training-template.yaml
# some valid image size and anchors:
# image_height: 416
# image_width: 416
# anchors: '10,13, 16,30, 33,23, 30,61, 62,45, 59,119, 116, 90, 156, 198, 373, 326'
# image_height: 608
# image_width: 608
# anchors: '12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401'

data_workers: 28
model_name: yolo
model_type: detection
strategy: aldd_yolo
image_height: 608
image_width: 608
batch_size: 16
anchors: '12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401'
confidence_thresh: 0.1
nms_thresh: 0.45
max_boxes: 50
# shm_size: '16G'
# gpu_id: '0,1,2,3'
# model_params_path: []
# task_id: cycle-node-mined-0
# class_names:
# - expose_rubbish